/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface LeadclickWidget {
    /**
     * The Facebook url
     */
    FBUrl?: string;
    /**
     * The Instagram url
     */
    IGUrl?: string;
    /**
     * The Whatsapp url
     */
    WAUrl?: string;
    /**
     * The background color
     */
    bgcolor: string;
    /**
     * The call to action message
     */
    cta: string;
    /**
     * The amount of connected integrations
     */
    integrations: number;
  }
}
declare global {
  interface HTMLLeadclickWidgetElement extends Components.LeadclickWidget, HTMLStencilElement {}
  var HTMLLeadclickWidgetElement: {
    prototype: HTMLLeadclickWidgetElement;
    new (): HTMLLeadclickWidgetElement;
  };
  interface HTMLElementTagNameMap {
    'leadclick-widget': HTMLLeadclickWidgetElement;
  }
}
declare namespace LocalJSX {
  interface LeadclickWidget {
    /**
     * The Facebook url
     */
    FBUrl?: string;
    /**
     * The Instagram url
     */
    IGUrl?: string;
    /**
     * The Whatsapp url
     */
    WAUrl?: string;
    /**
     * The background color
     */
    bgcolor?: string;
    /**
     * The call to action message
     */
    cta?: string;
    /**
     * The amount of connected integrations
     */
    integrations?: number;
  }
  interface IntrinsicElements {
    'leadclick-widget': LeadclickWidget;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'leadclick-widget': LocalJSX.LeadclickWidget & JSXBase.HTMLAttributes<HTMLLeadclickWidgetElement>;
    }
  }
}
