name: Continous deployment
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --ignore-scripts

      - name: Building
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run build
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && npm publish 

      # install dependencies and run semantic-release
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}